#!/usr/bin/env python3
import sys
import bank
from collections import Counter

def solve():
	filename = sys.argv[1]
	blocks = bank.read_file_as_blocks(filename)
	messages = bank.parse_session(blocks)
	
	for m in messages:
		print(m['type'])
	
	all_blocks = [b for m in messages for b in m['data']]
	counts = Counter(all_blocks)
	
	transfer_msg = None
	min_count = float('inf')
	
	for m in messages:
		if m['type'] == "TRANSFER":
			dst_block = m['data'][3]
			if counts[dst_block] < min_count:
				min_count = counts[dst_block]
				transfer_msg = m
	
	invoice_msg = None
	for m in messages:
		if m['type'] == "INVOICE":
			invoice_msg = m
			break

	if not transfer_msg or not invoice_msg:
		bank.write_blocks_to_file('task3.out', blocks)
		sys.exit(0)

	output_blocks = []
	for m in messages:
		if m is transfer_msg:
			data = list(m['data'])
			data[2] = invoice_msg['data'][3]
			output_blocks.extend(data)
		else:
			output_blocks.extend(m['data'])

	bank.write_blocks_to_file('task3.out', output_blocks)

if __name__ == "__main__":
	solve()