#!/usr/bin/env python3
import sys
import bank
from collections import Counter

def solve():
    filename = sys.argv[1]
    blocks = bank.read_file_as_blocks(filename)
    messages = bank.parse_session(blocks)

    for m in messages:
        print(m['type'])
    
    all_blocks = [b for m in messages for b in m['data']]
    global_counts = Counter(all_blocks)
    
    candidate_transfers = []
    
    for m in messages:
        if m['type'] == "TRANSFER":
            dst_block = m['data'][3]
            count = global_counts[dst_block]
            candidate_transfers.append((count, m))
    
    if not candidate_transfers:
        sys.stderr.write("Error: No transfer commands found in session.\n")
        sys.exit(0)

    candidate_transfers.sort(key=lambda x: x[0])
    target_msg = candidate_transfers[0][1]
    bank.write_blocks_to_file('task2.out', blocks + target_msg['data'])

if __name__ == "__main__":
    solve()