#!/usr/bin/env python3
import sys
import bank
from collections import Counter

def solve():
	filename = sys.argv[1]
	blocks = bank.read_file_as_blocks(filename)
	messages = bank.parse_session(blocks)
	
	for m in messages:
		print(m['type'])

	trans_cmd = None
	trans_time = None
	for m in messages:
		if m['type'] == "TRANSFER":
			trans_cmd = m['data'][1]
			trans_time = m['data'][4]
			break
			
	if not trans_cmd:
		bank.write_blocks_to_file('task4.out', blocks)
		sys.exit(0)
	
	all_blocks = [b for m in messages for b in m['data']]
	counts = Counter(all_blocks)
	
	target_invoice = None
	min_count = float('inf')
	
	for m in messages:
		if m['type'] == "INVOICE":
			payer_block = m['data'][2]
			if counts[payer_block] < min_count:
				min_count = counts[payer_block]
				target_invoice = m

	print(min_count)
	print(target_invoice)
				
	if not target_invoice:
		bank.write_blocks_to_file('task4.out', blocks)
		sys.exit(0)

	output_blocks = []
	for m in messages:
		if m is target_invoice:
			src = m['data'][0]
			dst = m['data'][2]
			amt = m['data'][3]
			
			new_msg = [
				src,
				trans_cmd,
				amt,
				dst,
				trans_time
			]
			output_blocks.extend(new_msg)
		else:
			output_blocks.extend(m['data'])

	bank.write_blocks_to_file('task4.out', output_blocks)

if __name__ == "__main__":
	solve()